# Generated by Django 6.0.3 on 2026-04-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_raw', models.CharField(max_length=255)),
                ('title_raw', models.CharField(max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('matched_via_llm', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.radiostation')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_path', models.CharField(blank=True, max_length=200)),
                ('container_selector', models.CharField(help_text='Selector for the wrapper containing all tracks', max_length=200)),
                ('artist_selector', models.CharField(help_text='Selector for the artist name', max_length=200)),
                ('track_title_selector', models.CharField(help_text='Selector for the track title', max_length=200)),
                ('requires_javascript', models.BooleanField(default=False)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scraper.radiostation')),
            ],
        ),
    ]
