# Generated by Django 6.0.3 on 2026-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperconfig',
            name='playlist_path',
        ),
        migrations.RemoveField(
            model_name='scraperconfig',
            name='requires_javascript',
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='json_artist_path',
            field=models.CharField(blank=True, help_text='Relative path to artist name inside an item', max_length=255),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='json_root_path',
            field=models.CharField(blank=True, help_text='Path to the tracks array', max_length=500),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='json_title_path',
            field=models.CharField(blank=True, help_text='Relative path to track title inside an item', max_length=255),
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='use_json_data',
            field=models.BooleanField(default=False, help_text='If checked, look for __NEXT_DATA__ before falling back to HTML'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='artist_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='container_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='track_title_selector',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
