# Generated by Django 6.0.3 on 2026-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_scraperconfig_playlist_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='show_name_selector',
            field=models.CharField(default='FILLER', max_length=255),
            preserve_default=False,
        ),
    ]
