# Generated by Django 6.0.3 on 2026-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scraperconfig_show_name_selector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperconfig',
            name='use_json_data',
        ),
        migrations.AddField(
            model_name='scraperconfig',
            name='scraper_type',
            field=models.CharField(choices=[('REQUESTS', 'Standard (Requests + HTML)'), ('CLOUDSCRAPER', 'Cloudscraper'), ('JSON_MAPPING', 'JSON Mapping (i.e. __NEXT_DATA__)')], default='STANDARD', max_length=20),
        ),
    ]
