# Generated by Django 6.0.3 on 2026-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_scraperconfig_scraper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperconfig',
            name='scraper_type',
            field=models.CharField(choices=[('STANDARD', 'Standard (Requests + HTML)'), ('CLOUDSCRAPER', 'Cloudscraper'), ('HEADLESS_BROWSER', 'Headless Browser (Playwright)'), ('JSON_MAPPING', 'JSON Mapping (i.e. __NEXT_DATA__)')], default='STANDARD', max_length=20),
        ),
    ]
