# Generated by Django 6.0.3 on 2026-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_scraperconfig_scraper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperconfig',
            name='parsing_strategy',
            field=models.CharField(choices=[('HTML_SELECTORS', 'HTML CSS Selectors'), ('JSON_MAPPING', 'Next.js JSON Mapping')], default='HTML_SELECTORS', help_text='How should we extract the data?', max_length=20),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='scraper_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Requests'), ('HEADLESS_BROWSER', 'Headless Browser (Playwright)')], default='STANDARD', help_text='How should we fetch the page?', max_length=20),
        ),
    ]
