# Generated by Django 6.0.3 on 2026-04-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_scraperconfig_parsing_strategy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedtrack',
            old_name='spotify_uri',
            new_name='youtube_id',
        ),
    ]
